controller_manager:
  ros__parameters:
    # FairinoHardwareInterface 中 ServoJ 的 cmdT = 0.008 s，
    # 因此真机控制周期设为 125 Hz。
    update_rate: 125

    fairino3_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


fairino3_controller:
  ros__parameters:
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6

    command_interfaces:
      - position

    state_interfaces:
      - position
